### ISSUE TITLE
I can't ignore my directories in Github 

### ISSUE THREAD

**Issue by VeroIarrachtai** [VeroIarrachtai/Abies_vs_ozone#5]
I have tried to ignore "Reference_Transcriptomics" directory, but I didin't do it.
[here is the directory to delete](https://github.com/VeroIarrachtai/Abies_vs_ozone/tree/master/4_Transcriptomics/metadata)

I added directory pathway in my ".gitignore" file.
[here is my .gitignore file](https://github.com/VeroIarrachtai/Abies_vs_ozone/blob/master/.gitignore)

**Comment by AliciaMstt** [comment]
That's weird. Can you run `git status` and paste what you see?

**Comment by VeroIarrachtai** [comment]
I deleted the "Reference_Transcriptomics" directory and included it again, in the same way I am including the heavy directories again and I haven't suffered same problems :)
